# Generated by Django 4.2.8 on 2023-12-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TradeYearIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "export_value_i",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "import_value_i",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "reporting_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_index_country",
                        to="wto.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeYearData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "export_value_y",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "import_value_y",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "partner_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_country",
                        to="wto.country",
                    ),
                ),
                (
                    "product_sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wto.productsector",
                    ),
                ),
                (
                    "reporting_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_year_country",
                        to="wto.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeQuarterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Quarter", models.IntegerField()),
                (
                    "export_value_q",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "import_value_q",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "reporting_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_quarter_country",
                        to="wto.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeMonthData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_value_m",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "import_value_m",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "reporting_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_month_country",
                        to="wto.country",
                    ),
                ),
            ],
        ),
    ]
