# Generated by Django 4.2.8 on 2023-12-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wto", "0004_trademonthdata_e_month_trademonthdata_i_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trademonthdata_e",
            name="year",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trademonthdata_i",
            name="year",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tradequarterdata_e",
            name="year",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tradequarterdata_i",
            name="year",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
