# Generated by Django 5.0 on 2024-01-01 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wto', '0007_country_l_productsector_l_commercialdata_i_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialData_E_Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('export_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('partner_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_country_e_individual', to='wto.country_l')),
                ('reporting_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_country_e_individual', to='wto.country_l')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialData_I_Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('import_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('partner_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_country_i_individual', to='wto.country_l')),
                ('reporting_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_country_i_individual', to='wto.country_l')),
            ],
        ),
    ]
