# Generated by Django 5.0 on 2024-01-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wto', '0009_productsector_mfn_mfn_a_mfn_b'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mfn_b',
            old_name='export_value',
            new_name='MFN_value',
        ),
    ]
