# Generated by Django 5.0 on 2024-01-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wto', '0010_rename_export_value_mfn_b_mfn_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeYearData_E_Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('export_value_y', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('partner_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_country_e_individual', to='wto.country')),
                ('product_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wto.productsector')),
                ('reporting_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_year_country_e_individual', to='wto.country')),
            ],
        ),
        migrations.CreateModel(
            name='TradeYearData_I_Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('import_value_y', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('partner_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_country_i_individual', to='wto.country')),
                ('product_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wto.productsector')),
                ('reporting_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_year_country_i_individual', to='wto.country')),
            ],
        ),
    ]
